### ISSUE TITLE
Missing 'Configi.php'

### ISSUE THREAD

**Issue by zahedkamal87** [markd87/Folder#1]
I'm getting these 2 errors.. 

```
Warning: require_once(configi.php): failed to open stream: No such file or directory in C:\xampp\htdocs\2pinboard\functions.php on line 3

Fatal error: require_once(): Failed opening required 'configi.php' (include_path='C:\xampp\php\PEAR') in C:\xampp\htdocs\2pinboard\functions.php on line 3
```

**Comment by markd87** [comment]
I added the configi.php file.
It simply contains the connection to the database, therefore if you want to use it you need to have a working database, and change the user, password, and database name in the file.
